image: node:18

stages:
  - deploy

pages:
  stage: deploy
  script:
    - npm ci
    - npx parcel build index.html --out-dir public --public-url "./" --no-cache
  artifacts:
    paths:
      - public
  only:
    - main
